apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: appsingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: freecodecamp
      port:
        number: 8080

  # rules:
  # - http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: freecodecamp
  #           port:
  #             number: 8080
