name: Build and Push Docker Image

on:
  push:
    branches:
      - development

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/esimim/freecodecamp-backenddevandapi:latest

    - name: Set up kubeconfig
      run:  |
        mkdir $HOME/.kube
        echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.28.4'
      id: install
    
    - name: List objects
      run: kubectl get all -n apps
    # - name: deploy to kubernetes
    #   run: kubectl apply -n apps Deployment-freeCodeCamp.yaml
    