name: Build and Push Docker Image

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        tags: esimim/eliandro-app:latest
        context: .
        push: true
